clear all;
close all;
clc;

%%

trainTable = readtable("exports/biasModels/modelsTrainBIC.csv");
tableProps = trainTable.Properties.VariableNames;

[alpha_All,exp_r_All,xp_All] = spm_BMS(-0.5*[trainTable.MBSK_all, ...
    trainTable.MBDK_all,trainTable.NMB_all,trainTable.Bias_all])

[alpha_C,exp_r_C,xp_C] = spm_BMS(-0.5*[trainTable.MBSK_C_all, ...
    trainTable.MBDK_C_all,trainTable.NMB_C_all,trainTable.Bias_C_all])

[alpha_NC,exp_r_NC,xp_NC,xp] = spm_BMS(-0.5*[trainTable.MBSK_NC_all, ...
    trainTable.MBDK_NC_all,trainTable.NMB_NC_all,trainTable.Bias_NC_all])

%%

varNames = {'dummy','Trials','alpha_MBSK','expR_MBSK','xp_MBSK', ...
    'alpha_MBDK','expR_MBDK','xp_MBDK', ...
    'alpha_NMB','expR_NMB','xp_NMB', ...
    'alpha_Bias','expR_Bias','xp_Bias'};
varTypes = {'string','string','string','string','string', ...
    'string','string','string', ...
    'string','string','string', ...
    'string','string','string'};

% Create an empty table (0 rows)
outputTable = table('Size',[0 numel(varNames)], ...
    'VariableTypes',varTypes, ...
    'VariableNames',varNames);

outputTable(end+1,:) = {'dummy','All', ...
    fixNumberString(alpha_All(1)),fixNumberString(exp_r_All(1)), ...
    fixNumberString(xp_All(1)),fixNumberString(alpha_All(2)), ...
    fixNumberString(exp_r_All(2)),fixNumberString(xp_All(2)), ...
    fixNumberString(alpha_All(3)),fixNumberString(exp_r_All(3)), ...
    fixNumberString(xp_All(3)),fixNumberString(alpha_All(4)), ...
    fixNumberString(exp_r_All(4)),fixNumberString(xp_All(4))};

outputTable(end+1,:) = {'dummy','Chunkable', ...
    fixNumberString(alpha_C(1)),fixNumberString(exp_r_C(1)), ...
    fixNumberString(xp_C(1)),fixNumberString(alpha_C(2)), ...
    fixNumberString(exp_r_C(2)),fixNumberString(xp_C(2)), ...
    fixNumberString(alpha_C(3)),fixNumberString(exp_r_C(3)), ...
    fixNumberString(xp_C(3)),fixNumberString(alpha_C(4)), ...
    fixNumberString(exp_r_C(4)),fixNumberString(xp_C(4))};

outputTable(end+1,:) = {'dummy','Non-chunkable', ...
    fixNumberString(alpha_NC(1)),fixNumberString(exp_r_NC(1)), ...
    fixNumberString(xp_NC(1)),fixNumberString(alpha_NC(2)), ...
    fixNumberString(exp_r_NC(2)),fixNumberString(xp_NC(2)), ...
    fixNumberString(alpha_NC(3)),fixNumberString(exp_r_NC(3)), ...
    fixNumberString(xp_NC(3)),fixNumberString(alpha_NC(4)), ...
    fixNumberString(exp_r_NC(4)),fixNumberString(xp_NC(4))};

%%

outputTable.alpha_Bias(1) = sprintf("\\textbf{%s}",outputTable.alpha_Bias(1));
outputTable.alpha_Bias(2) = sprintf("\\textbf{%s}",outputTable.alpha_Bias(2));

outputTable.expR_Bias(1) = sprintf("\\textbf{%s}",outputTable.expR_Bias(1));
outputTable.expR_Bias(2) = sprintf("\\textbf{%s}",outputTable.expR_Bias(2));

outputTable.xp_Bias(1) = sprintf("\\textbf{%s}",outputTable.xp_Bias(1));
outputTable.xp_Bias(2) = sprintf("\\textbf{%s}",outputTable.xp_Bias(2));

outputTable.alpha_NMB(3) = sprintf("\\textbf{%s}",outputTable.alpha_NMB(3));

outputTable.expR_NMB(3) = sprintf("\\textbf{%s}",outputTable.expR_NMB(3));

outputTable.xp_NMB(3) = sprintf("\\textbf{%s}",outputTable.xp_NMB(3));

writetable(outputTable,"exports/biasModels/modelsTrainBIC_SPMBMS_table.csv");

%%

% Create an empty table (0 rows)
outputTable2 = table('Size',[0 numel(varNames)], ...
    'VariableTypes',varTypes, ...
    'VariableNames',varNames);

outputTable2(end+1,:) = {'dummy','All', ...
    alpha_All(1),exp_r_All(1), ...
    xp_All(1),alpha_All(2), ...
    exp_r_All(2),xp_All(2), ...
    alpha_All(3),exp_r_All(3), ...
    xp_All(3),alpha_All(4), ...
    exp_r_All(4),xp_All(4)};

outputTable2(end+1,:) = {'dummy','Chunkable', ...
    alpha_C(1),exp_r_C(1), ...
    xp_C(1),alpha_C(2), ...
    exp_r_C(2),xp_C(2), ...
    alpha_C(3),exp_r_C(3), ...
    xp_C(3),alpha_C(4), ...
    exp_r_C(4),xp_C(4)};

outputTable2(end+1,:) = {'dummy','Non-chunkable', ...
    alpha_NC(1),exp_r_NC(1), ...
    xp_NC(1),alpha_NC(2), ...
    exp_r_NC(2),xp_NC(2), ...
    alpha_NC(3),exp_r_NC(3), ...
    xp_NC(3),alpha_NC(4), ...
    exp_r_NC(4),xp_NC(4)};

writetable(outputTable2,"exports/biasModels/modelsTrainBIC_SPMBSM_df.csv");

%%

function output = fixNumberString(value)
    if (value==0)
        output = "0";
        return;
    end

    timer = 0;
    if (value<=1e-3)
        while (value<1)
            value = value*10;
            timer = timer+1;
        end
    end
    
    if (timer>0)
        output = sprintf("$%.3g \\times 10^{-%d}$",value,timer);
    elseif (value>1)
        output = sprintf("%.3g",value);
    else
        output = sprintf("%.3f",value);
    end
end