clear all;
close all;
clc;

%%

for i = 0:3
    fileNameRead = "exports/biasModels/temp/BICFitsFinal/modelsTrainBIC" + num2str(i) + ".csv";
    trainTable = readtable(fileNameRead);
    tableProps = trainTable.Properties.VariableNames;
    
    [alpha_All,exp_r_All,xp_All] = spm_BMS(-0.5*[trainTable.MBSK_all, ...
        trainTable.MBDK_all,trainTable.Bias_all,trainTable.NMB_all]);
    xp_All

    varNames = {'dummy','Trials','alpha_MBSK','expR_MBSK','xp_MBSK', ...
        'alpha_MBDK','expR_MBDK','xp_MBDK', ...
        'alpha_Bias','expR_Bias','xp_Bias', ...
        'alpha_NMB','expR_NMB','xp_NMB'};
    varTypes = {'string','string','string','string','string', ...
        'string','string','string', ...
        'string','string','string', ...
        'string','string','string'};
        
    % Create an empty table (0 rows)
    outputTable2 = table('Size',[0 numel(varNames)], ...
        'VariableTypes',varTypes, ...
        'VariableNames',varNames);

    outputTable2(end+1,:) = {'dummy','All', ...
        alpha_All(1),exp_r_All(1), ...
        xp_All(1),alpha_All(2), ...
        exp_r_All(2),xp_All(2), ...
        alpha_All(3),exp_r_All(3), ...
        xp_All(3),alpha_All(4), ...
        exp_r_All(4),xp_All(4)};
    
    fileNameSave = "exports/biasModels/temp/BICFitsFinal/modelsTrainBIC_SPMBSM_df" + num2str(i) + ".csv";
    writetable(outputTable2,fileNameSave);
end